// File : COMMAND_TARGET.h // Generated by Django Backend
#ifndef __COMMAND_TARGET_H__
#define __COMMAND_TARGET_H__

#include <stdio.h>

class COMMAND_TARGET {
public:
    struct MsgBody {
        unsigned short ccuTrackId; // Auto-generated
        unsigned short radTrackId; // Auto-generated
        float trackConfidence; // Auto-generated
        double speed; // Auto-generated
        int direction; // Auto-generated

        // Print Functions
        void print(char pstr[], int len);
        void printBrief(char pstr[], int len);
    } msg;

    bool set(unsigned char msg[], unsigned short &size);
    bool decode(unsigned char msg[], unsigned short size);
    bool isValid();
    void ntoh();
    void hton();
    void print(char pstr[], int len);
    void print(FILE *fp);
    void print();
    void printBrief(char pstr[], int len);
    void printBrief(FILE *fp);
    void printBrief();
    void printMin(char pstr[], int len);
    COMMAND_TARGET();
};

#endif
